In [38]:
import numpy as np

In [39]:
x = np.arange(15, dtype=np.int32).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
x[1:, ::2] = -99 # from row 1 and taking step of 2
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [41]:
x.max(axis=1)

array([ 4,  8, 13])

In [42]:
arr  = np.array([1,2,3,4])
arr1 = np.zeros(3)
arr2 = np.ones(2)
arr3 = np.empty(3)
arr4 = np.arange(4)
arr5 = np.arange(2, 9, 3)
arr6 = np.linspace(0, 10, num=5) # spaced linearly in space
print(arr, arr1, arr2, arr3, arr4, arr5, arr6)

[1 2 3 4] [0. 0. 0.] [1. 1.] [0. 0. 0.] [0 1 2 3] [2 5 8] [ 0.   2.5  5.   7.5 10. ]


In [43]:
a = [1,2,3]
b = [4,5,6]
arr7 = np.concatenate((a, b))
arr7

array([1, 2, 3, 4, 5, 6])

In [44]:
c = np.arange(20)
print(c)
d = c.reshape(4,5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4, 5, 6]


In [53]:
# import cv2 as cv
arr01 = np.arange(15)

arr02 = arr01[np.newaxis, :]
arr03 = arr02[:, np.newaxis]

print(arr01.shape, arr02.shape, arr03.shape)
arr01, arr02, arr03

(15,) (1, 15) (1, 1, 15)


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]]))

In [55]:
arr04 = np.expand_dims(arr03, axis=1)
arr04

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]]])

In [62]:
# print(arr04[arr04 < 5])
list_c = list(zip([5, 2],[6, 8]))
for coord in list_c:
    print(coord)

(5, 6)
(2, 8)
